### PR TITLE
Add authorizer to sls

### PR DESCRIPTION
**Pull request by elcorbs**

### CODE REVIEW

**Review by humulla — APPROVED** [review]
Looks good, have you removed the api keys section?

**Comment by elcorbs** [comment]
> Looks good, have you removed the api keys section?

No! Good catch :)

**Comment by humulla** [comment]
Also, what about adding the authorizer to the custom section of the serverless.yml?

**Comment by elcorbs** [comment]
> Also, what about adding the authorizer to the custom section of the serverless.yml?

I've changed it to get the arn's from system manager parameter store instead of hardcoding them so that it can be easily changed for all APIs if we change the authorizer arn.

**Pull request merged**
